### ISSUE TITLE
难道不知道hosts不支持通配符的吗？

### ISSUE THREAD

**Issue by null4n** [kmahyyg/ban_cnshort#3]
hosts只支持单一域名啊，难道都不知道的吗？通配符域名可以用dnsmasq指定一个不存在的DNS来解析……………

**Comment by kmahyyg** [comment]
我这里是可以的......可能实现不一样吧......

感谢提醒, 即将修复.

**Comment by kmahyyg** [comment]
已修复，感谢。

**Comment by null4n** [comment]
印象中dnsmasq要指定通配符好像是
.douyin.com这样的？另外如果是在路由器的话127.0.0.1应该会直接向路由器本地的DNS查询吧，我在路由器上用255.255.255.255或者10.0.0.1之类不存在的IP

**Comment by kmahyyg** [comment]
已修复，使用 255.255.255.254。不加 `.`  也是泛域名解析。 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*
